services:

  # Minio
  minio:
    container_name: minio
    image: minio/minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      - test-network
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  minio-init:
    container_name: minio-init
    image: minio/mc
    depends_on:
      - minio
    networks:
      - test-network
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minio minio123; do
        echo 'Waiting for MinIO server to start';
        sleep 2;
      done;
      mc mb local/warehouse --ignore-existing;
      mc policy set public local/warehouse;
      echo 'Done';
      "

  # Postgres
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - test-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # Spark
  spark-master:
    image: custom-spark-governance:latest
    container_name: spark-master
    build:
      context: .
      dockerfile: Dockerfile_spark_custom
    environment:
      - PYTHONPATH=/app
      - AWS_REGION=us-east-1
    ports:
      - '8080:8080'
      - '7077:7077'
    networks:
      - test-network
    volumes:
      - .:/app
    user: root
    command: >
      /bin/bash -c "
      pip install --no-cache-dir -r /app/requirements.txt &&
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      "

  spark-worker:
    image: custom-spark-governance:latest
    container_name: spark-worker
    environment:
      - PYTHONPATH=/app
      - AWS_REGION=us-east-1
    networks:
      - test-network
    volumes:
      - .:/app
    user: root
    depends_on:
      - spark-master
    command: >
      /bin/bash -c "
      pip install --no-cache-dir -r /app/requirements.txt &&
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
      "

volumes:
  postgres_data:
    name: postgres_data
  minio_data:
    name: minio_data

networks:
  test-network:
    driver: bridge
    name: test-network