FROM apache/spark:3.5.1-scala2.12-java17-python3-r-ubuntu

USER root

WORKDIR /app

RUN /opt/spark/bin/spark-sql \
    --master "local[*]" \
    --packages org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.6.1,\
org.apache.iceberg:iceberg-aws-bundle:1.6.1,\
org.apache.hadoop:hadoop-aws:3.3.4,\
org.postgresql:postgresql:42.7.1 \
    -e "SELECT 1;"

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

USER spark