import json
import logging
from pathlib import Path

import pytest

from src.config.logging import setup_logging
from src.modules.ai_governance.ai_governance_main import ai_governance_main

setup_logging()
test_logger = logging.getLogger("test")

TEST_MODE = "prod" # test or prod - data_dir and prod_config are different
TARGET_TABLE_NAME = "medical_records"

DATA_DIR = Path(__file__).parents[3] / "data" / TEST_MODE
GROUND_TRUTH_DIR = DATA_DIR / "metadata"


def load_ground_truth_from_json(file_path: Path):
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    truth_map = {}
    for col in data["columns"]:
        truth_map[col["column_name"]] = {
            "sensitivity_tag": col["sensitivity_tag"],
            "sensitivity_level": col["sensitivity_level"],
        }

    return truth_map

def fetch_predicted_metadata(pg_client, table_name: str):
    """
    Fetch predicted metadata generated by the AI Classification module from PostgreSQL.
    """

    sql = """
          SELECT c.column_name, c.sensitivity_tag, c.sensitivity_level, c.detection_method, c.confidence_score
          FROM columns_metadata c
                   JOIN tables_metadata t ON c.table_id = t.table_id
          WHERE t.table_name = :table_name \
          """

    rows = pg_client.execute_query(sql, {"table_name": table_name})

    pred_map = {}
    for row in rows:
        pred_map[row["column_name"]] = {
            "sensitivity_tag": row["sensitivity_tag"].upper(),
            "sensitivity_level": row["sensitivity_level"].upper(),
            "detection_method": row["detection_method"],
            "confidence_score": row["confidence_score"]
        }
    return pred_map

def calculate_pii_scores(ground_truth: dict, predictions: dict) -> dict:
    """
    Calculate Precision, Recall, F1-Score, and Severity Level Accuracy metrics.
    Decoupled function to allow reuse in notebooks or analytical UIs without re-running the AI pipeline.
    """

    tp = 0  # True Positive: Actually PII and Predicted as PII (Any level except NONE)
    fp = 0  # False Positive: Actually NONE but Predicted as PII
    fn = 0  # False Negative: Actually PII but Predicted as NONE
    tn = 0  # True Negative: Actually NONE and Predicted as NONE

    correct_level_count = 0
    total_columns = len(ground_truth)

    for col_name, truth in ground_truth.items():
        pred = predictions.get(col_name)

        if not pred:
            test_logger.warning(f"Missing prediction for column: {col_name}")
            pytest.fail(f"Missing prediction for column: {col_name}")

        is_truth_pii = truth["sensitivity_tag"] != "NONE"
        is_pred_pii = pred["sensitivity_tag"] != "NONE"

        # 1. Binary Classification (Is PII vs. Is Not PII)
        if is_truth_pii and is_pred_pii:
            tp += 1
        elif not is_truth_pii and is_pred_pii:
            fp += 1
        elif is_truth_pii and not is_pred_pii:
            fn += 1
        else:
            tn += 1

        # 2. Multi-class Classification (Sensitivity Level)
        if truth["sensitivity_level"] == pred["sensitivity_level"]:
            correct_level_count += 1

    # 3. Calculate Precision, Recall, F1-Score
    precision = tp / (tp + fp) if tp + fp > 0 else 0.0
    recall = tp / (tp + fn) if tp + fn > 0 else 0.0
    f1_score = 2 * (precision * recall) / (precision + recall) if precision + recall > 0 else 0.0
    level_accuracy = correct_level_count / total_columns if total_columns > 0 else 0.0

    return {
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "precision": precision,
        "recall": recall,
        "f1_score": f1_score,
        "level_accuracy": level_accuracy
    }

@pytest.mark.parametrize("target_table_name", [
    TARGET_TABLE_NAME,
])
def test_full_governance_scores_e2e(spark_session, pg_client, test_config, prod_config, target_table_name):
    """
    End-to-End Integration Test for the Smart Data Governance Pipeline.
    - Triggers the AI Classification Pipeline to extract Iceberg structures and sync targets to PostgreSQL.
    - Extracts generated live metadata from DB and evaluates performance KPIs against Ground Truth JSONs.
    """

    test_logger.info("\n" + "=" * 500)
    test_logger.info("-" * 25 + f"[PERFORMANCE] Starting AI Governance E2E Integration Test" + "-" * 25)
    test_logger.info(f"Target Configuration: {target_table_name if target_table_name else 'ALL CONFIGURED TABLES'}")

    tables_to_evaluate = []

    # Ensure physical infrastructure requirements are satisfied before evaluation
    if not DATA_DIR.exists():
        pytest.fail(f"Configured DATA_DIR does not exist: {DATA_DIR.resolve()}")
    if not GROUND_TRUTH_DIR.exists():
        pytest.fail(f"Configured GROUND_TRUTH_DIR does not exist: {GROUND_TRUTH_DIR.resolve()}")

    if target_table_name:
        # Specific table designated: auto-append name to evaluation matrix list
        tables_to_evaluate.append(target_table_name)
    else:
        # Discovery scanning: list out all distinct tables matching source extensions found within DATA_DIR
        source_files = list(DATA_DIR.glob("*.csv")) + list(DATA_DIR.glob("*.json"))
        tables_to_evaluate = [f.stem for f in source_files]

    if not tables_to_evaluate:
        pytest.skip(f"No operational source data tables discovered in {DATA_DIR.resolve()}. Skipping matrix.")

    perf_config = test_config["test_suite"]["test_performance"]
    target_precision = float(perf_config["target_precision"])
    target_recall = float(perf_config["target_recall"])
    target_f1_score = float(perf_config["target_f1_score"])
    target_accuracy = float(perf_config["target_accuracy"])

    # 1. AI Governance
    target_param = target_table_name if target_table_name else ""

    test_logger.info("Triggering AI Governance Pipeline orchestration to process target datasets...")
    try:
        if TEST_MODE == "test":
            ai_governance_main(target_table=target_param, config=test_config)
        else:
            ai_governance_main(target_table=target_param, config=prod_config)
        test_logger.info("AI Governance main execution completed. Classification tags persisted to PostgreSQL.")
    except Exception as e:
        pytest.fail(f"AI Governance Pipeline execution failed due to an infrastructural exception: {e}")

    # 2. Calculate PII Classification Metrics
    test_logger.info("\n" + "-" * 25 + " EVALUATING PIPELINE ACCURACY METRICS " + "-" * 25)

    for table in tables_to_evaluate:
        gt_json_path = GROUND_TRUTH_DIR / f"{table}_metadata.json"

        if not gt_json_path.exists():
            test_logger.warning(
                f"Skipping evaluation for table '{table}'. Ground Truth schema file missing at: {gt_json_path.resolve()}")
            continue

        test_logger.info(f"[Evaluation Step] Processing accuracy assessment matrix for target: {table}")

        # Get ground truth and predictions
        ground_truth = load_ground_truth_from_json(gt_json_path)
        predictions = fetch_predicted_metadata(pg_client, table)

        metrics = calculate_pii_scores(ground_truth, predictions)

        # Metrics Report
        test_logger.info(
            f"   Confusion Matrix Results     : TP={metrics['tp']} | FP={metrics['fp']} | FN={metrics['fn']} | TN={metrics['tn']}")
        test_logger.info(f"   Calculated Precision Metric  : {metrics['precision']:.4f}")
        test_logger.info(f"   Calculated Recall Metric     : {metrics['recall']:.4f}")
        test_logger.info(f"   Calculated F1-Score Metric   : {metrics['f1_score']:.4f}")
        test_logger.info(f"   Calculated Level Accuracy    : {metrics['level_accuracy']:.4f}")

        # Formal Assessment Dashboard Output matching the benchmark standard
        test_logger.info("\n" + "=" * 25 + " [PERFORMANCE] PII CLASSIFICATION ACCURACY ASSESSMENT MATRIX " + "=" * 25)
        test_logger.info(f"Target Table Assessment          : {table}")
        test_logger.info("-" * 79)
        test_logger.info(f"Metric Targeted Assessment       : PII PRECISION")
        test_logger.info(f"   Global Aggregated Precision    : {metrics['precision']:.4f} (target >= {target_precision:.2f})")
        test_logger.info("-" * 79)
        test_logger.info(f"Metric Targeted Assessment       : PII RECALL")
        test_logger.info(f"   Global Aggregated Precision    : {metrics['recall']:.4f} (target >= {target_recall:.2f})")
        test_logger.info("-" * 79)
        test_logger.info(f"Metric Targeted Assessment       : PII F1-SCORE")
        test_logger.info(f"   Global Aggregated F1-Score    : {metrics['f1_score']:.4f} (target >= {target_f1_score:.2f})")
        test_logger.info("-" * 79)
        test_logger.info(f"Metric Targeted Assessment       : LEVEL ACCURACY")
        test_logger.info(f"   Global Aggregated Accuracy    : {metrics['level_accuracy']:.4f} (target >= {target_accuracy:.2f})")
        test_logger.info("=" * 79 + "\n")


        assert metrics[
                   "precision"] >= 0.85, f"SLA breached for table {table}. Precision {metrics['precision']:.4f} fell below threshold 0.85"
        assert metrics[
                   "recall"] >= 0.90, f"SLA breached for table {table}. Recall {metrics['recall']:.4f} fell below threshold 0.90"
        assert metrics[
                   "f1_score"] >= 0.87, f"SLA breached for table {table}. F1-Score {metrics['f1_score']:.4f} fell below threshold 0.87"
        assert metrics[
                   "level_accuracy"] >= 0.80, f"SLA breached for table {table}. Sensitivity Level Accuracy {metrics['level_accuracy']:.4f} fell below threshold 0.80"

    test_logger.info("=" * 79)
    test_logger.info("E2E INTEGRATION TEST SUITE EXECUTED AND VERIFIED SUCCESSFULLY!")
    test_logger.info("=" * 79 + "\n")